name: deploy-container

on:
  push:
    branches:
      - main
    paths:
      - "packages/container/**"
defaults:
  run:
    working-directory: packages/container/

jobs:
  build:
    runs-on: ubuntu-latest

<<<<<<< Updated upstream
  steps:
    - uses: actions/checkout@v3
    - run: npm install
    - run: npm run build
=======
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run build
>>>>>>> Stashed changes
